### ISSUE TITLE
Use codes as the index instead of integers

### ISSUE THREAD

**Issue by johncblandii** [cloudposse/terraform-aws-service-quotas#7]
### Describe the Feature

```hcl
quotas_to_manage         = { for i, quota in var.service_quotas : i => quota if local.enabled && lookup(quota, "value", null) != null }
```

[This code ](https://github.com/cloudposse/terraform-aws-service-quotas/blob/6bc3cea2f55865aaf02d9f65c8a01289f6cf4073/main.tf#L5-L12) uses the index which means reordering the list of services changes the requests.

### Expected Behavior

Reordering the list of services does not create new/duplicate requests.

### Use Case

If we wanted to keep related quotas grouped together, it would create new quota requests if 2 became 3 or similar.

Example stack yaml:

```
        service_quotas_enabled: true
        service_quotas:
          - quota_name: Subnets per VPC
            service_code: vpc
            value: 250
          - quota_code: L-E79EC296 # aka `Security Groups per Region`
            service_code: vpc
            value: 2500
          - quota_code: L-F678F1CE # aka `VPC per Region`
            service_code: vpc
            value: null
          - quota_code: L-0263D0A3 # aka `EC2-VPC Elastic IPs`
            service_code: ec2
            value: 10
          - quota_code: L-36FBB829 # aka `Fargate Spot vCPU resource count`
            service_code: fargate
            value: 250
          - quota_code: L-3032A538 # aka `Fargate On-Demand vCPU resource count`
            service_code: fargate
            value: 250
```

### Describe Ideal Solution

Stack yaml can be reordered however we see fit and it doesn't create new resources.

### Alternatives Considered

One alternative is to use a map instead of a list of quotas.

### Additional Context

https://github.com/cloudposse/terraform-aws-service-quotas/blob/6bc3cea2f55865aaf02d9f65c8a01289f6cf4073/main.tf#L5-L12
